# Generated by Django 3.1 on 2020-08-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=400)),
                ('number', models.IntegerField()),
                ('page_count', models.IntegerField()),
            ],
        ),
    ]
