# Generated by Django 3.1 on 2020-08-26 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_auto_20200825_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='ages',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='booksapp.ages'),
        ),
    ]
