# Generated by Django 3.1 on 2020-08-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0003_auto_20200826_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ages',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
