# Generated by Django 3.1 on 2020-09-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0004_auto_20200826_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
