# Generated by Django 3.1 on 2020-09-02 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0006_auto_20200902_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='uu',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
