# Generated by Django 3.1 on 2020-09-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0007_book_uu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uu',
        ),
    ]
